- name: render SQL template
  template:
    src: create_db_and_user.sql.j2
    dest: "/tmp/create_db_and_user.sql"
    mode: 0600


- name: render pgpass file
  template:
    src: pgpass.j2
    dest: "/tmp/pgpass"
    mode: 0600


- name: Create user and DB
  shell: "PGPASSFILE=/tmp/pgpass psql -U postgres -p {{ _apb_provision_creds.DB_PORT }} -h {{ _apb_provision_creds.DB_HOST }}.{{ namespace }} -f /tmp/create_db_and_user.sql"
  register: pgout
  failed_when: pgout.rc != 0


- name: encode provision credentials
  asb_encode_binding:
    fields:
      DB_TYPE: postgres
      DB_HOST: "{{ _apb_provision_creds.DB_HOST }}"
      DB_PORT: "{{ _apb_provision_creds.DB_PORT }}"
      DB_USER: "{{ postgresql_new_user }}"
      DB_PASSWORD: "{{ postgresql_new_password }}"
      DB_NAME: "{{ postgresql_new_database }}"
