apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresql
spec:
  clusterServiceClassExternalName: dh-postgresql-apb
  clusterServicePlanExternalName: dev
  parameters:
    app_name: "postgresql"
    postgresql_database: "admin"
    postgresql_password: "admin"
    postgresql_user: "admin"
    postgresql_version: "9.6"
