- name: Deploy rhscl-postgresql-apb to "{{ cluster }}"
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    state: absent
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: rhscl-postgresql-apb-bind
    install_python_requirements: yes
