- name: set service state to {{ state }}
  k8s_v1_service:
    name: postgresql
    namespace: '{{ namespace }}'
    labels:
      app: rhscl-postgresql-apb
      service: postgresql
    selector:
      app: rhscl-postgresql-apb
      service: postgresql
    ports:
    - name: port-5432
      port: 5432
      protocol: TCP
      target_port: 5432
    state: "{{ state }}"
  register: postgres_service

- name: scale deployment down
  k8s_extensions_v1beta1_deployment:
    name: postgresql
    namespace: '{{ namespace }}'
    replicas: 0
    state: present
    labels:
      app: rhscl-postgresql-apb
      service: postgresql
  when: state == 'absent'

- include_tasks: dev.yml
  when: _apb_plan_id == "dev"

- include_tasks: prod.yml
  when: _apb_plan_id == "prod"

- name: delete replication controller
  k8s_v1_replication_controller:
    name: postgresql-1
    namespace: '{{ namespace }}'
    state: absent
  when: state == 'absent'

- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: postgres
      DB_HOST: postgresql
      DB_PORT: "5432"
      DB_USER: "{{ postgresql_user }}"
      DB_PASSWORD: "{{ postgresql_password }}"
      DB_NAME: "{{ postgresql_database }}"
  when: state == 'present'
